In [1]:
import pandas as pd

import datetime as dt

In [2]:
job_data_csv = pd.read_csv("data/job_postings_2019.csv")
job_data_csv.head()

,crawl_timestamp,url,job_title,category,company_name,city,state,country,inferred_city,inferred_state,...,job_description,job_type,salary_offered,job_board,geo,cursor,contact_email,contact_phone_number,uniq_id,html_job_description
0,2019-02-06 05:26:22 +0000,https://www.indeed.com/viewjob?jk=fd83355c2b23...,Enterprise Data Scientist I,Accounting/Finance,Farmers Insurance Group,Woodland Hills,CA,Usa,Woodland hills,California,...,Read what people are saying about working here...,Undefined,NaN,indeed,usa,1549432819114777,NaN,NaN,3b6c6acfcba6135a31c83bd7ea493b18,NaN
1,2019-02-06 05:33:41 +0000,https://www.dice.com/jobs/detail/Data-Scientis...,Data Scientist,NaN,Luxoft USA Inc,Middletown,NJ,Usa,Middletown,New jersey,...,We have an immediate opening for a Sharp Data ...,Undefined,NaN,dice,usa,1549432819122106,NaN,NaN,741727428839ae7ada852eebef29b0fe,NaN
2,2019-02-06 05:33:35 +0000,https://www.dice.com/jobs/detail/Data-Scientis...,Data Scientist,NaN,Cincinnati Bell Technology Solutions,New York,NY,Usa,New york,New york,...,Candidates should have the following backgroun...,Full Time,NaN,dice,usa,1549432819236156,NaN,NaN,cdc9ef9a1de327ccdc19cc0d07dbbb37,NaN
3,2019-02-06 05:33:42 +0000,https://www.indeed.com/viewjob?jk=841edd86ead2...,"Data Scientist, Aladdin Wealth Tech, Associate...",Accounting/Finance,BlackRock,New York,NY 10055 (Midtown area),Usa,New york,New york,...,Read what people are saying about working here...,Undefined,NaN,indeed,usa,1549432819259473,NaN,NaN,1c8541cd2c2c924f9391c7d3f526f64e,NaN
4,2019-02-06 05:48:23 +0000,https://job-openings.monster.com/senior-data-s...,Senior Data Scientist,biotech,CyberCoders,Charlotte,NC,Usa,Charlotte,North carolina,...,We are seeking an extraordinary Data Scientist...,Full Time,NaN,monster,usa,1549436429015957,NaN,NaN,445652a560a5441060857853cf267470,NaN

In [3]:
#check which columns have few null values out of city/state and keep that column

In [4]:
job_data_csv['state'].isna().sum()

416

In [5]:
job_data_csv['inferred_state'].isna().sum()

516

In [6]:
job_data_csv['city'].isna().sum()

249

In [7]:
job_data_csv['inferred_city'].isna().sum()

1020

In [8]:
job_data_csv['country'].isna().sum()

0

In [9]:
job_data = job_data_csv.drop(columns=['crawl_timestamp','url',
                                      'job_description','geo','cursor','contact_email',
                                      'contact_phone_number','uniq_id','html_job_description',"inferred_state",
                                      "inferred_city",'inferred_country'])

job_data.head()

,job_title,category,company_name,city,state,country,post_date,job_type,salary_offered,job_board
0,Enterprise Data Scientist I,Accounting/Finance,Farmers Insurance Group,Woodland Hills,CA,Usa,2019-02-06,Undefined,NaN,indeed
1,Data Scientist,NaN,Luxoft USA Inc,Middletown,NJ,Usa,2019-02-05,Undefined,NaN,dice
2,Data Scientist,NaN,Cincinnati Bell Technology Solutions,New York,NY,Usa,2019-02-05,Full Time,NaN,dice
3,"Data Scientist, Aladdin Wealth Tech, Associate...",Accounting/Finance,BlackRock,New York,NY 10055 (Midtown area),Usa,2019-02-06,Undefined,NaN,indeed
4,Senior Data Scientist,biotech,CyberCoders,Charlotte,NC,Usa,2019-02-05,Full Time,NaN,monster

In [10]:
#drop all rows with null values in city, state
job_data.dropna(subset = ["city","state"], inplace=True)
job_data

,job_title,category,company_name,city,state,country,post_date,job_type,salary_offered,job_board
0,Enterprise Data Scientist I,Accounting/Finance,Farmers Insurance Group,Woodland Hills,CA,Usa,2019-02-06,Undefined,NaN,indeed
1,Data Scientist,NaN,Luxoft USA Inc,Middletown,NJ,Usa,2019-02-05,Undefined,NaN,dice
2,Data Scientist,NaN,Cincinnati Bell Technology Solutions,New York,NY,Usa,2019-02-05,Full Time,NaN,dice
3,"Data Scientist, Aladdin Wealth Tech, Associate...",Accounting/Finance,BlackRock,New York,NY 10055 (Midtown area),Usa,2019-02-06,Undefined,NaN,indeed
4,Senior Data Scientist,biotech,CyberCoders,Charlotte,NC,Usa,2019-02-05,Full Time,NaN,monster
...,...,...,...,...,...,...,...,...,...,...
9988,UX Data Scientist w/Python for R&D Design Cent...,computer jobs,OSI Engineering,San Francisco,CA,Usa,2019-09-30,Full Time,NaN,monster
9989,Data Scientist,Computer-or-internet,Echo Global Logistics,Computer-or-internet,Computer-or-internet,US,2019-09-20,Undefined,NaN,indeed
9990,Data Scientist,Computer-or-internet,"Metron, Inc.",Computer-or-internet,Computer-or-internet,US,2019-09-01,Undefined,NaN,indeed
9991,"Siri - Embedded Data Scientist, Data Organization",Computer-or-internet,Apple,Computer-or-internet,Computer-or-internet,US,2019-09-01,Undefined,NaN,indeed
9992,Geology/Geo-Data Scientist,Engineering-or-architecture,"Albany, OR",Albany,OR,US,2019-10-01,Undefined,NaN,indeed

In [11]:
remote = job_data.loc[job_data["state"] == "Computer-or-internet"]
remote.head()

,job_title,category,company_name,city,state,country,post_date,job_type,salary_offered,job_board
5603,Data Scientist,Computer-or-internet,Company Info Follow Get job updates from BD BD...,Computer-or-internet,Computer-or-internet,US,2019-07-03,Undefined,NaN,indeed
5819,Data Scientist,Computer-or-internet,Company Info Follow Get job updates from Veriz...,Computer-or-internet,Computer-or-internet,US,2019-07-19,Undefined,NaN,indeed
5825,Data Scientist,Computer-or-internet,Company Info Follow Get job updates from Disco...,Computer-or-internet,Computer-or-internet,US,2019-08-01,Undefined,NaN,indeed
7350,Data Scientist,Computer-or-internet,Riverside Research 17 reviews - Wright-Patters...,Computer-or-internet,Computer-or-internet,US,2019-08-15,Undefined,NaN,indeed
7391,Data Scientist,Computer-or-internet,"BD 2,151 reviews - New Jersey",Computer-or-internet,Computer-or-internet,US,2019-07-20,Undefined,NaN,indeed

In [12]:
remote["city"].count()

18

In [13]:
job_data.dtypes

job_title         object
category          object
company_name      object
city              object
state             object
country           object
post_date         object
job_type          object
salary_offered    object
job_board         object
dtype: object

In [14]:
salary_notnull = job_data[job_data.salary_offered.notnull()]

In [15]:
job_type = job_data["job_type"].value_counts()
job_type

Undefined     5901
Full Time     3188
Contract       486
Part Time        5
Internship       2
Name: job_type, dtype: int64

In [16]:
job_title = job_data["job_title"].value_counts()
job_title

Data Scientist                                                   2787
Senior Data Scientist                                             626
Sr. Data Scientist                                                193
Lead Data Scientist                                               170
Principal Data Scientist                                          145
                                                                 ...
Top Secret - Data Scientist / Engineer!                             1
Data Scientist Lead (R and Python)                                  1
Data Scientist - Agriculture Commodity Research Engine (ACRE)       1
Risk & Market Strategy/Data Scientist                               1
Data Scientist / Cognitive Developer                                1
Name: job_title, Length: 2687, dtype: int64

In [17]:
#pd.set_option('display.max_row', 3000)

# Set iPython's max column width to 50
#pd.set_option('display.max_columns', 20)

In [18]:
title_df = pd.DataFrame(job_title)
title_df.head(5)

                          job_title
Data Scientist                 2787
Senior Data Scientist           626
Sr. Data Scientist              193
Lead Data Scientist             170
Principal Data Scientist        145

In [19]:
#clean state names: that conatins'work-from-home, computer,united' ---> remote
loc = ['work','computer','united']

for x in loc:
    
    wfh = job_data[job_data['state'].str.contains(x, case=False)]
    wfh_list = wfh['state'].to_list()
    job_data["state"].replace(wfh_list,"Remote",inplace=True)

In [20]:
job_data['state'].value_counts()

CA                             1485
NY                              567
VA                              511
TX                              494
MA                              477
                               ...
IL 60602 (Loop area)              1
NY 11050                          1
NC 28255                          1
Engineering-or-architecture       1
CA 91767                          1
Name: state, Length: 770, dtype: int64

In [21]:
nj = job_data[job_data['state'].str.contains("jersey", case=False)]
nj_list = nj['state'].to_list()
job_data["state"].replace(nj_list,"NJ",inplace=True)

In [22]:
job_data['state'] = job_data['state'].str.split(" ").str[0]
job_data

,job_title,category,company_name,city,state,country,post_date,job_type,salary_offered,job_board
0,Enterprise Data Scientist I,Accounting/Finance,Farmers Insurance Group,Woodland Hills,CA,Usa,2019-02-06,Undefined,NaN,indeed
1,Data Scientist,NaN,Luxoft USA Inc,Middletown,NJ,Usa,2019-02-05,Undefined,NaN,dice
2,Data Scientist,NaN,Cincinnati Bell Technology Solutions,New York,NY,Usa,2019-02-05,Full Time,NaN,dice
3,"Data Scientist, Aladdin Wealth Tech, Associate...",Accounting/Finance,BlackRock,New York,NY,Usa,2019-02-06,Undefined,NaN,indeed
4,Senior Data Scientist,biotech,CyberCoders,Charlotte,NC,Usa,2019-02-05,Full Time,NaN,monster
...,...,...,...,...,...,...,...,...,...,...
9988,UX Data Scientist w/Python for R&D Design Cent...,computer jobs,OSI Engineering,San Francisco,CA,Usa,2019-09-30,Full Time,NaN,monster
9989,Data Scientist,Computer-or-internet,Echo Global Logistics,Computer-or-internet,Remote,US,2019-09-20,Undefined,NaN,indeed
9990,Data Scientist,Computer-or-internet,"Metron, Inc.",Computer-or-internet,Remote,US,2019-09-01,Undefined,NaN,indeed
9991,"Siri - Embedded Data Scientist, Data Organization",Computer-or-internet,Apple,Computer-or-internet,Remote,US,2019-09-01,Undefined,NaN,indeed
9992,Geology/Geo-Data Scientist,Engineering-or-architecture,"Albany, OR",Albany,OR,US,2019-10-01,Undefined,NaN,indeed

In [23]:
 job_data['state'].value_counts()

CA                             2007
NY                              824
TX                              665
VA                              663
MA                              557
IL                              525
WA                              436
PA                              367
NJ                              366
FL                              304
MD                              293
GA                              293
NC                              272
DC                              236
CO                              192
OH                              182
MI                              168
CT                              150
MO                              138
MN                              124
AZ                              116
Remote                          107
UT                               59
OR                               58
TN                               58
IN                               54
WI                               44
AL                               41
AR                               34
NV                               26
DE                               21
KS                               20
SC                               19
NE                               17
RI                               17
KY                               15
LA                               13
NH                               13
IA                               13
ID                               12
OK                               12
ME                                9
WV                                7
NM                                7
Virginia                          6
HI                                3
ND                                3
MT                                2
Idaho                             2
PR                                2
Hawaii                            2
MS                                1
NN                                1
Washington                        1
Massachusetts                     1
New                               1
VT                                1
Louisiana                         1
Engineering-or-architecture       1
Name: state, dtype: int64

In [24]:
job_data = job_data.loc[job_data["state"] != "Engineering-or-architecture"]
job_data['state'].value_counts()

CA               2007
NY                824
TX                665
VA                663
MA                557
IL                525
WA                436
PA                367
NJ                366
FL                304
MD                293
GA                293
NC                272
DC                236
CO                192
OH                182
MI                168
CT                150
MO                138
MN                124
AZ                116
Remote            107
UT                 59
OR                 58
TN                 58
IN                 54
WI                 44
AL                 41
AR                 34
NV                 26
DE                 21
KS                 20
SC                 19
RI                 17
NE                 17
KY                 15
IA                 13
LA                 13
NH                 13
ID                 12
OK                 12
ME                  9
NM                  7
WV                  7
Virginia            6
ND                  3
HI                  3
Idaho               2
PR                  2
MT                  2
Hawaii              2
MS                  1
NN                  1
Washington          1
Massachusetts       1
New                 1
VT                  1
Louisiana           1
Name: state, dtype: int64

In [25]:

names = ['senior','sr','principal','lead','junior','jr','intern','phd','data', 'chief','vp','associate']
replace_names=['Senior DS','Senior DS','Principal DS', 'Lead DS',
               'Junior DS','Junior DS', 'DS Intern', 'DS PhD','Data Scientist','Chief DS', 'VP DS','Associate DS']

names_order = ['chief','vp','phd','senior','sr','jr','junior','principal','lead','intern','associate','data']
replace_order = ['Chief DS','VP DS','DS PhD','Senior DS','Senior DS','Junior DS','Junior DS','Principal DS','Lead DS','DS Intern',
                'Asscoiate DS','Data Scientist']

In [26]:
len(names_order)

12

In [27]:
len(replace_order)

12

In [28]:
for x in range(12):
    title = job_data[job_data['job_title'].str.contains(names_order[x], case=False)]
    title_list = title['job_title'].to_list()
    job_data["job_title"].replace(title_list,replace_order[x],inplace=True)

C:\Users\vinoy\anaconda3\envs\Pythondata\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [29]:
job_data["job_title"].value_counts()

Data Scientist    6181
Senior DS         2117
Lead DS            400
Principal DS       327
Asscoiate DS       174
Junior DS          142
DS Intern          104
Chief DS            56
DS PhD              43
VP DS               37
Name: job_title, dtype: int64

In [30]:
### state names
abbrev = ['New','virginia','Hawaii','Idaho','Louisiana','Washington','Massachusetts']
replace_abbrev = ["NM","VA","HI","ID","LA","WA","MA"]

for x in range(7):
    
    abb = job_data[job_data['state'].str.contains(abbrev[x], case=False)]
    abb_list = abb['state'].to_list()
    job_data["state"].replace(abb_list,replace_abbrev[x],inplace=True)

In [31]:
len(job_data['state'].value_counts())

51

In [32]:
job_data

,job_title,category,company_name,city,state,country,post_date,job_type,salary_offered,job_board
0,Data Scientist,Accounting/Finance,Farmers Insurance Group,Woodland Hills,CA,Usa,2019-02-06,Undefined,NaN,indeed
1,Data Scientist,NaN,Luxoft USA Inc,Middletown,NJ,Usa,2019-02-05,Undefined,NaN,dice
2,Data Scientist,NaN,Cincinnati Bell Technology Solutions,New York,NY,Usa,2019-02-05,Full Time,NaN,dice
3,Asscoiate DS,Accounting/Finance,BlackRock,New York,NY,Usa,2019-02-06,Undefined,NaN,indeed
4,Senior DS,biotech,CyberCoders,Charlotte,NC,Usa,2019-02-05,Full Time,NaN,monster
...,...,...,...,...,...,...,...,...,...,...
9988,Data Scientist,computer jobs,OSI Engineering,San Francisco,CA,Usa,2019-09-30,Full Time,NaN,monster
9989,Data Scientist,Computer-or-internet,Echo Global Logistics,Computer-or-internet,Remote,US,2019-09-20,Undefined,NaN,indeed
9990,Data Scientist,Computer-or-internet,"Metron, Inc.",Computer-or-internet,Remote,US,2019-09-01,Undefined,NaN,indeed
9991,Data Scientist,Computer-or-internet,Apple,Computer-or-internet,Remote,US,2019-09-01,Undefined,NaN,indeed
9992,Data Scientist,Engineering-or-architecture,"Albany, OR",Albany,OR,US,2019-10-01,Undefined,NaN,indeed

In [33]:
g = job_data['city'].value_counts()

In [34]:
pd.set_option('display.max_row', 3000)

# Set iPython's max column width to 50
pd.set_option('display.max_columns', 20)
city_df = pd.DataFrame(g)
city_df

                          city
New York                   684
San Francisco              474
Chicago                    304
Boston                     293
Seattle                    276
Washington                 229
Atlanta                    208
Los Angeles                195
Charlotte                  148
Austin                     146
Arlington                  133
Houston                    125
Philadelphia               109
Dallas                     104
Sunnyvale                  104
Mountain View              101
McLean                      95
San Jose                    92
Palo Alto                   91
Cambridge                   87
Tampa                       84
Glen Mills                  83
Irving                      83
San Diego                   76
Denver                      75
Columbus                    74
United States               73
Irvine                      64
Bellevue                    64
Reston                      61
Menlo Park                  61
Santa Clara                 60
Alexandria                  60
Cincinnati                  55
Redmond                     53
Phoenix                     52
St. Louis                   50
Alpharetta                  50
Pittsburgh                  50
Stamford                    49
Fairfax                     47
Jersey City                 45
Minneapolis                 45
Santa Clara Valley          44
Lake Forest                 43
Herndon                     42
Baltimore                   41
Santa Monica                41
Hartford                    41
Detroit                     41
Tempe                       39
Dearborn                    39
Miami                       38
Orlando                     37
Waltham                     36
Redwood City                36
Jacksonville                35
Plano                       34
Rockville                   33
Portland                    33
South San Francisco         32
Fort Worth                  32
New York City               32
Raleigh                     32
Annapolis Junction          31
San Antonio                 31
Richmond                    31
Chantilly                   31
San Mateo                   30
Malvern                     28
Indianapolis                28
Springfield                 28
Richardson                  27
Plymouth Meeting            26
Bethesda                    26
Bentonville                 25
Birmingham                  25
Salt Lake City              24
El Segundo                  23
Santa Ana                   23
Carlsbad                    22
Peapack                     22
Nashville                   22
Columbia                    22
Boulder                     21
Broomfield                  21
Kansas City                 21
Santa Cruz                  20
Eden Prairie                20
Fort Meade                  20
San Bruno                   20
Morrisville                 20
Wellesley                   20
Durham                      20
Charlottesville             19
Wilmington                  19
Foster City                 19
Chesterfield                19
Torrance                    18
Ann Arbor                   18
Northbrook                  18
East Hanover                17
West Hollywood              17
Naperville                  17
Computer-or-internet        17
Madison                     16
Creve Coeur                 16
Glendale                    16
Englewood                   16
Pasadena                    15
Scott AFB                   15
Armonk                      15
Remote                      15
Huntsville                  15
Silver Spring               15
Memphis                     15
Louisville                  14
Hoboken                     14
Florham Park                14
Norfolk                     14
Princeton                   14
Lexington                   14
Newport Beach               14
Boca Raton                  13
Greenwich                   13
Westwood                    13
Edison                      13
Las Vegas                   13
Lakewood                    13
North Reading               12
Melbourne                   12
Woodbridge                  12
Costa Mesa                  12
Troy                        12
Franklin                    12
Dayton                      12
Santa Barbara               12
Rochester                   12
Spring                      11
Newark                      11
Scottsdale                  11
Piscataway                  11
Long Beach                  11
Berkeley                    11
Cary                        11
Pennington                  11
Thousand Oaks               11
Norcross                    11
Milpitas                    11
Rancho Cordova              11
Parsippany                  11
Oak Brook                   11
Secaucus                    11
Scotts Valley               10
Greeley                     10
Boise                       10
Pleasanton                  10
Monterey                    10
New Brunswick               10
Frederick                   10
Weston                      10
MacDill AFB                 10
Milwaukee                   10
Vienna                      10
Woodcliff Lake              10
Hampton                     10
Fort Lauderdale              9
Minnetonka                   9
Lisle                        9
Linthicum                    9
East Palo Alto               9
Ashburn                      9
Manhattan                    9
Bolingbrook                  9
Providence                   9
Addison                      9
Auburn Hills                 9
Rosemead                     9
Middletown                   9
Richfield                    9
Totowa                       8
La Jolla                     8
Wayzata                      8
Cleveland                    8
Richland                     8
Basking Ridge                8
Aberdeen                     8
Mc Lean                      8
Stanford                     8
Fort Mill                    8
Bloomfield                   8
Hershey                      8
Saint Paul                   8
Dublin                       8
Mason                        8
Coppell                      8
Grand Rapids                 7
Fort Belvoir                 7
Lewisville                   7
Needham                      7
Oswego                       7
Hillsboro                    7
Culver City                  7
East Hartford                7
Beaverton                    7
Athens                       7
Rome                         7
Bothell                      7
Greensboro                   7
Maplewood                    7
Lehi                         7
Cupertino                    7
Owings Mills                 7
Worcester                    7
Suitland                     7
Lincoln                      7
Offutt AFB                   7
Riverton                     6
MIDDLE CITY WEST             6
Green Bay                    6
Mooresville                  6
Glenview                     6
Fremont                      6
Davis                        6
Rosslyn                      6
Horsham                      6
Greenville                   6
Tucson                       6
Schaumburg                   6
Tysons                       6
Renton                       6
Norwell                      6
Downers Grove                6
Oakland                      6
Saint Louis                  6
Morgantown                   6
Rosemont                     6
Franklin Lakes               6
Centennial                   6
Conshohocken                 6
Port Washington              6
Maryland Heights             6
Draper                       6
Bedford                      6
Golden                       6
Itasca                       6
Tulsa                        6
Littleton                    6
Riverwoods                   6
Wayne                        6
Leawood                      6
Plymouth                     6
Virginia                     6
Abbott Park                  6
King of Prussia              5
Juno Beach                   5
San Ramon                    5
Falls Church                 5
Research Triangle Park       5
Marietta                     5
Akron                        5
Lowell                       5
New Orleans                  5
Burlington                   5
Albany                       5
Woodbridge Township          5
Vancouver                    5
Round Rock                   5
The Woodlands                5
Fenton                       5
Beaufort                     5
La CaÃ±ada Flintridge         5
Southborough                 5
New Jersey                   5
Medford                      5
Campbell                     5
Albuquerque                  5
New Britain                  5
Oak Ridge                    5
Charleston                   5
Altamonte Springs            5
College Station              5
Menomonee Falls              5
Raritan                      5
Aurora                       5
Fort Myers                   5
Bellingham                   5
Morristown                   5
Danvers                      5
Roseland                     4
Langley AFB                  4
Mclean                       4
Groton                       4
Moorestown                   4
Berwyn                       4
Grand Blanc                  4
Concord                      4
Angels                       4
Hanover                      4
Lenexa                       4
Oklahoma City                4
Bradenton                    4
Morton                       4
Watertown                    4
West Menlo Park              4
Shreveport                   4
Johns Creek                  4
Quantico                     4
Hoffman Estates              4
Bedminster                   4
Lexington Park               4
Buffalo                      4
Arden Hills                  4
Saint Joseph                 4
Cave Springs                 4
Bloomington                  4
Dedham                       4
Livermore                    4
Oldsmar                      4
Sterling                     4
West Palm Beach              4
ISAFA                        4
MIDDLE CITY EAST             4
Neptune Beach                4
Laurel                       4
Colorado Springs             4
Burr Ridge                   4
Los Gatos                    4
Deerfield                    4
Brooklyn                     4
Shawnee                      4
Manchester                   4
Skokie                       3
Dulles                       3
Bar Harbor                   3
Marlow Heights               3
Coraopolis                   3
Berwick                      3
Johnston                     3
Ladue                        3
Knoxville                    3
Ada                          3
Corona                       3
Andover                      3
Titusville                   3
Jefferson                    3
Peoria                       3
Summit                       3
South Jordan                 3
Purchase                     3
Huntington Beach             3
Manhattan Beach              3
Smithfield                   3
Bolling AFB                  3
Pullman                      3
Toledo                       3
Little Rock                  3
Omaha                        3
Framingham                   3
Honolulu                     3
Woodland Hills               3
Brookline                    3
Burlingame                   3
Lake Mary                    3
Rocky Hill                   3
Westminster                  3
HOUSTON                      3
Carrollton                   3
Spring House                 3
Carmel                       3
Bronx                        3
Township of Warren           3
High Point                   3
Woodlawn                     3
Sugar Land                   3
Faribault                    3
Chester                      3
Hunters Creek Village        3
Weehawken                    3
Washington D.c.              3
Merrifield                   3
MOFFETT FIELD                3
Branchville                  3
Greenwood Village            3
Broadview Heights            3
Towson                       3
Elkridge                     3
Aliso Viejo                  3
College Park                 3
Lawrence Township            3
Portsmouth                   3
Park City                    3
Reno                         3
Kentwood                     3
Tacoma                       3
Lemont                       3
Minden                       3
Estero                       3
Fort Huachuca                3
Evanston                     3
Villanova                    3
OAK BROOK                    3
Decatur                      3
Woburn                       3
Cedar Rapids                 3
Topeka                       3
San Francisco Bay Area       3
Lawrenceville                3
Windsor Mill                 3
Elk Grove                    3
Rolling Meadows              3
Linthicum Heights            3
Evergreen                    3
Chapel Hill                  3
Yonkers                      3
Granville                    3
Winston-Salem                3
Loveland                     3
West Lafayette               2
Champaign                    2
Liverpool                    2
Rockleigh                    2
Redondo Beach                2
Bowie                        2
West Des Moines              2
Inver Grove Heights          2
Ventura                      2
Ewing Township               2
Skippack                     2
Aguadilla                    2
Dayton (Fairborn)            2
Anacostia                    2
Livonia                      2
Cottonwood Heights           2
Ridgefield                   2
Urbandale                    2
Durham County                2
Bernards                     2
Hanscom Air Force Base       2
Baton Rouge                  2
Vinings                      2
Cedar Falls                  2
Arnold                       2
Palmdale                     2
Bartlesville                 2
Saint Petersburg             2
Bismarck                     2
Farmington Hills             2
Emeryville                   2
Bakersfield                  2
Westlake                     2
North Brunswick Township     2
Anne Arundel County          2
Fulton                       2
Allen                        2
Marlborough                  2
Miramar                      2
Chesapeake                   2
Gahanna                      2
Allentown                    2
Clearwater                   2
Whitehall                    2
Miami Lakes                  2
Manassas                     2
Rancho Santa Margarita       2
Southlake                    2
Time                         2
Lancaster                    2
Redwood Shores               2
Albemarle                    2
Timonium                     2
Union                        2
Catonsville                  2
Foxborough                   2
Melrose Park                 2
Deerfield Beach              2
Lake Angelus                 2
Metairie                     2
Radnor                       2
PECK SLIP                    2
Morris Plains                2
Carle Place                  2
Tallahassee                  2
Chelmsford                   2
Parsippany-Troy Hills        2
Collegeville                 2
Fort Gordon                  2
Des Plaines                  2
Hawaii                       2
Provo                        2
Buffalo Grove                2
Shelton                      2
Work at Home                 2
Idaho                        2
Flagstaff                    2
Michigan Center              2
Hattontown                   2
Englewood Cliffs             2
Hill AFB                     2
North Wales                  2
Foothill Ranch               2
Lakeland                     2
Moline                       2
Helena                       2
Duluth                       2
Kent                         2
Melville                     2
Findlay                      2
Miami Beach                  2
Hilliard                     2
Round Lake                   2
San Diego County             2
Trenton                      2
Malibu                       2
Longmont                     2
Egg Harbor Township          2
Atlantic City                2
Fishers                      2
Norwalk                      2
Pomona                       2
Patuxent River               2
Palm Beach Gardens           2
Clarkson Valley              2
Belcamp                      2
Salem                        2
Dunwoody                     2
Tysons Corner                2
Jackson                      2
Southbury                    2
Dalton                       2
Macon                        2
Norwood                      2
Santa Fe                     2
Manawa                       2
Iselin                       2
New york                     1
Sunrise                      1
Clarion                      1
Uniontown                    1
Kenilworth                   1
Seal Beach                   1
Henrico County               1
Blue Bell                    1
Carson City                  1
Centreville                  1
ÐšÐ¸ÐµÐ²                         1
Denton                       1
Sun Prairie                  1
Holyoke                      1
Aberdeen Proving Ground      1
HOFFMAN EST                  1
West Mclean                  1
Short Hills                  1
Plainsboro Center            1
Playa del Rey                1
Oxnard                       1
Hayward                      1
Newcastle                    1
Reynoldsburg                 1
Dallas-Fort Worth            1
Ames                         1
Weatherby Lake               1
Belmont                      1
Niskayuna                    1
Upper Marlboro               1
Fallon                       1
Centerville                  1
Villa Park                   1
West Hempstead               1
Jessup                       1
Sacramento                   1
Montgomery County            1
Bridgewater                  1
Ogden                        1
Novi                         1
Beloit                       1
Northfield                   1
Sloan                        1
Somerville                   1
Glen Allen                   1
Katy                         1
Roslindale                   1
Marlboro                     1
Appleton                     1
Cranford                     1
Peterborough                 1
Warrington                   1
Avon                         1
Brier                        1
Lebanon                      1
Tonawanda                    1
Franklin Township            1
Malta                        1
Lanham                       1
Fredericksburg               1
Niceville                    1
West New York                1
Colma                        1
Altanta                      1
Brunswick                    1
Olathe                       1
Rutherford                   1
Centralia                    1
Cheswick                     1
Bellaire                     1
Offutt Air Force Base        1
Clarksburg                   1
Brentwood                    1
Murray Hill                  1
PICATINNY ARS                1
Helmetta                     1
South Amboy                  1
Encino                       1
Wood Dale                    1
Tinton Falls                 1
Fort Bragg                   1
Warwick                      1
Virginia Beach               1
Wake County                  1
Mettawa                      1
MCLEAN                       1
Lees Summit                  1
Panama                       1
East Rutherford              1
LaGrange                     1
Gaithersburg                 1
Homestead AFB                1
Roanoke                      1
New Freedom                  1
Depew                        1
Universal City               1
Elmhurst                     1
Lackawanna                   1
Oakland Park                 1
Newtown                      1
North Tonawanda              1
Cochran                      1
Wauwatosa                    1
Camden                       1
Forest Hills                 1
KNG OF PRUSSA                1
South Valley Stream          1
Southfield                   1
Westbrook                    1

In [35]:
city_data = ['work','computer','united']

for x in city_data:
    
    wfh = job_data[job_data['city'].str.contains(x, case=False)]
    wfh_list = wfh['city'].to_list()
    job_data["city"].replace(wfh_list,"Remote",inplace=True)

C:\Users\vinoy\anaconda3\envs\Pythondata\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

In [36]:
job_data['city'].value_counts()

New York                    684
San Francisco               474
Chicago                     304
Boston                      293
Seattle                     276
Washington                  229
Atlanta                     208
Los Angeles                 195
Charlotte                   148
Austin                      146
Arlington                   133
Houston                     125
Philadelphia                109
Remote                      107
Dallas                      104
Sunnyvale                   104
Mountain View               101
McLean                       95
San Jose                     92
Palo Alto                    91
Cambridge                    87
Tampa                        84
Irving                       83
Glen Mills                   83
San Diego                    76
Denver                       75
Columbus                     74
Irvine                       64
Bellevue                     64
Reston                       61
Menlo Park                   61
Alexandria                   60
Santa Clara                  60
Cincinnati                   55
Redmond                      53
Phoenix                      52
St. Louis                    50
Alpharetta                   50
Pittsburgh                   50
Stamford                     49
Fairfax                      47
Minneapolis                  45
Jersey City                  45
Santa Clara Valley           44
Lake Forest                  43
Herndon                      42
Santa Monica                 41
Detroit                      41
Hartford                     41
Baltimore                    41
Dearborn                     39
Tempe                        39
Miami                        38
Orlando                      37
Waltham                      36
Redwood City                 36
Jacksonville                 35
Plano                        34
Portland                     33
Rockville                    33
New York City                32
Fort Worth                   32
South San Francisco          32
Raleigh                      32
Chantilly                    31
Annapolis Junction           31
San Antonio                  31
Richmond                     31
San Mateo                    30
Springfield                  28
Indianapolis                 28
Malvern                      28
Richardson                   27
Plymouth Meeting             26
Bethesda                     26
Birmingham                   25
Bentonville                  25
Salt Lake City               24
El Segundo                   23
Santa Ana                    23
Nashville                    22
Peapack                      22
Carlsbad                     22
Columbia                     22
Boulder                      21
Broomfield                   21
Kansas City                  21
Santa Cruz                   20
Eden Prairie                 20
Wellesley                    20
Morrisville                  20
San Bruno                    20
Durham                       20
Fort Meade                   20
Chesterfield                 19
Wilmington                   19
Foster City                  19
Charlottesville              19
Torrance                     18
Northbrook                   18
Ann Arbor                    18
West Hollywood               17
Naperville                   17
East Hanover                 17
Englewood                    16
Madison                      16
Creve Coeur                  16
Glendale                     16
Huntsville                   15
Memphis                      15
Silver Spring                15
Scott AFB                    15
Pasadena                     15
Armonk                       15
Newport Beach                14
Norfolk                      14
Princeton                    14
Florham Park                 14
Hoboken                      14
Lexington                    14
Louisville                   14
Edison                       13
Boca Raton                   13
Greenwich                    13
Las Vegas                    13
Westwood                     13
Lakewood                     13
Melbourne                    12
Woodbridge                   12
Costa Mesa                   12
Franklin                     12
Dayton                       12
North Reading                12
Santa Barbara                12
Troy                         12
Rochester                    12
Thousand Oaks                11
Piscataway                   11
Norcross                     11
Parsippany                   11
Milpitas                     11
Secaucus                     11
Spring                       11
Rancho Cordova               11
Pennington                   11
Long Beach                   11
Cary                         11
Scottsdale                   11
Oak Brook                    11
Berkeley                     11
Newark                       11
Vienna                       10
Frederick                    10
New Brunswick                10
Milwaukee                    10
Weston                       10
Monterey                     10
Pleasanton                   10
Hampton                      10
Scotts Valley                10
Woodcliff Lake               10
Boise                        10
MacDill AFB                  10
Greeley                      10
Rosemead                      9
Linthicum                     9
East Palo Alto                9
Richfield                     9
Middletown                    9
Bolingbrook                   9
Minnetonka                    9
Auburn Hills                  9
Lisle                         9
Addison                       9
Fort Lauderdale               9
Ashburn                       9
Providence                    9
Manhattan                     9
Saint Paul                    8
Hershey                       8
Basking Ridge                 8
La Jolla                      8
Stanford                      8
Richland                      8
Totowa                        8
Fort Mill                     8
Mc Lean                       8
Mason                         8
Aberdeen                      8
Coppell                       8
Wayzata                       8
Dublin                        8
Cleveland                     8
Bloomfield                    8
Lincoln                       7
Athens                        7
Greensboro                    7
Oswego                        7
Lehi                          7
Rome                          7
Grand Rapids                  7
Lewisville                    7
Owings Mills                  7
Worcester                     7
Fort Belvoir                  7
Culver City                   7
Needham                       7
Beaverton                     7
East Hartford                 7
Bothell                       7
Maplewood                     7
Hillsboro                     7
Offutt AFB                    7
Suitland                      7
Cupertino                     7
Greenville                    6
Maryland Heights              6
Virginia                      6
Bedford                       6
Riverwoods                    6
Plymouth                      6
Rosslyn                       6
Franklin Lakes                6
Centennial                    6
Itasca                        6
Schaumburg                    6
Morgantown                    6
Wayne                         6
Abbott Park                   6
Tulsa                         6
Conshohocken                  6
Oakland                       6
Port Washington               6
Davis                         6
Saint Louis                   6
Rosemont                      6
Green Bay                     6
MIDDLE CITY WEST              6
Downers Grove                 6
Draper                        6
Norwell                       6
Fremont                       6
Tysons                        6
Renton                        6
Horsham                       6
Leawood                       6
Riverton                      6
Golden                        6
Mooresville                   6
Glenview                      6
Littleton                     6
Tucson                        6
College Station               5
Vancouver                     5
Medford                       5
Morristown                    5
Beaufort                      5
New Britain                   5
Fort Myers                    5
Danvers                       5
Fenton                        5
Round Rock                    5
San Ramon                     5
New Jersey                    5
Bellingham                    5
Campbell                      5
Woodbridge Township           5
Akron                         5
La CaÃ±ada Flintridge          5
New Orleans                   5
Menomonee Falls               5
King of Prussia               5
Oak Ridge                     5
Research Triangle Park        5
Albuquerque                   5
Lowell                        5
The Woodlands                 5
Aurora                        5
Charleston                    5
Albany                        5
Altamonte Springs             5
Raritan                       5
Juno Beach                    5
Falls Church                  5
Burlington                    5
Southborough                  5
Marietta                      5
Roseland                      4
MIDDLE CITY EAST              4
Brooklyn                      4
Quantico                      4
Sterling                      4
Lenexa                        4
Laurel                        4
Morton                        4
Los Gatos                     4
Burr Ridge                    4
Groton                        4
Hanover                       4
Manchester                    4
Grand Blanc                   4
Saint Joseph                  4
Langley AFB                   4
Oklahoma City                 4
Shreveport                    4
Deerfield                     4
Arden Hills                   4
Shawnee                       4
Oldsmar                       4
Berwyn                        4
Bloomington                   4
Cave Springs                  4
Bradenton                     4
Lexington Park                4
Angels                        4
ISAFA                         4
Neptune Beach                 4
Colorado Springs              4
Livermore                     4
Watertown                     4
Mclean                        4
Concord                       4
Dedham                        4
Hoffman Estates               4
Bedminster                    4
West Palm Beach               4
Moorestown                    4
West Menlo Park               4
Johns Creek                   4
Buffalo                       4
Ladue                         3
Jefferson                     3
Burlingame                    3
Broadview Heights             3
HOUSTON                       3
Minden                        3
Peoria                        3
Elk Grove                     3
Framingham                    3
Aliso Viejo                   3
Titusville                    3
Carmel                        3
Honolulu                      3
Portsmouth                    3
Andover                       3
Rocky Hill                    3
Brookline                     3
Smithfield                    3
Manhattan Beach               3
Summit                        3
Purchase                      3
Bar Harbor                    3
Skokie                        3
Hunters Creek Village         3
Lawrenceville                 3
Linthicum Heights             3
Lawrence Township             3
Washington D.c.               3
Kentwood                      3
Estero                        3
Evanston                      3
Rolling Meadows               3
Merrifield                    3
Topeka                        3
High Point                    3
Woodland Hills                3
Lake Mary                     3
Faribault                     3
Marlow Heights                3
Knoxville                     3
South Jordan                  3
Huntington Beach              3
Decatur                       3
Westminster                   3
Elkridge                      3
Coraopolis                    3
Lemont                        3
Spring House                  3
Cedar Rapids                  3
Loveland                      3
Carrollton                    3
College Park                  3
Branchville                   3
Park City                     3
OAK BROOK                     3
Chapel Hill                   3
Granville                     3
Tacoma                        3
Fort Huachuca                 3
Berwick                       3
Township of Warren            3
Villanova                     3
Yonkers                       3
Weehawken                     3
Johnston                      3
Pullman                       3
Bolling AFB                   3
Woodlawn                      3
Evergreen                     3
Chester                       3
Ada                           3
Winston-Salem                 3
Greenwood Village             3
Sugar Land                    3
Towson                        3
Little Rock                   3
Omaha                         3
MOFFETT FIELD                 3
Corona                        3
San Francisco Bay Area        3
Bronx                         3
Reno                          3
Toledo                        3
Windsor Mill                  3
Dulles                        3
Woburn                        3
Time                          2
Inver Grove Heights           2
PECK SLIP                     2
Redwood Shores                2
Morris Plains                 2
Flagstaff                     2
Southlake                     2
West Des Moines               2
Jackson                       2
Ventura                       2
Findlay                       2
Dayton (Fairborn)             2
Round Lake                    2
Hanscom Air Force Base        2
Hattontown                    2
Chelmsford                    2
North Wales                   2
Anacostia                     2
Hawaii                        2
Emeryville                    2
Marlborough                   2
Englewood Cliffs              2
Des Plaines                   2
Moline                        2
Idaho                         2
Allen                         2
Lake Angelus                  2
Parsippany-Troy Hills         2
Bartlesville                  2
Cedar Falls                   2
Fishers                       2
Bakersfield                   2
Miramar                       2
Rancho Santa Margarita        2
Carle Place                   2
Allentown                     2
Albemarle                     2
Norwood                       2
Baton Rouge                   2
Kent                          2
Tallahassee                   2
Deerfield Beach               2
Melville                      2
Anne Arundel County           2
Gahanna                       2
Chesapeake                    2
North Brunswick Township      2
Michigan Center               2
Hill AFB                      2
Helena                        2
Arnold                        2
Bismarck                      2
Pomona                        2
Farmington Hills              2
Foothill Ranch                2
Lakeland                      2
Hilliard                      2
Belcamp                       2
Catonsville                   2
Clearwater                    2
Fulton                        2
Whitehall                     2
Buffalo Grove                 2
Union                         2
Norwalk                       2
Clarkson Valley               2
Malibu                        2
Ewing Township                2
Macon                         2
Westlake                      2
Foxborough                    2
Redondo Beach                 2
Dunwoody                      2
Trenton                       2
Provo                         2
Cottonwood Heights            2
Palm Beach Gardens            2
Dalton                        2
Miami Beach                   2
Aguadilla                     2
Shelton                       2
Champaign                     2
Metairie                      2
West Lafayette                2
Duluth                        2
Fort Gordon                   2
Saint Petersburg              2
Livonia                       2
Bowie                         2
Lancaster                     2
Vinings                       2
Collegeville                  2
Bernards                      2
Rockleigh                     2
Patuxent River                2
Longmont                      2
Skippack                      2
Timonium                      2
Radnor                        2
San Diego County              2
Santa Fe                      2
Southbury                     2
Tysons Corner                 2
Palmdale                      2
Ridgefield                    2
Miami Lakes                   2
Manawa                        2
Atlantic City                 2
Durham County                 2
Manassas                      2
Urbandale                     2
Salem                         2
Liverpool                     2
Melrose Park                  2
Egg Harbor Township           2
Iselin                        2
Cranberry Township            1
Newcastle                     1
Montreal                      1
BOWLING GREEN                 1
White River Junction          1
Idaho Falls                   1
Bridgewater                   1
Woonsocket                    1
Katy                          1
West Mclean                   1
Marlboro                      1
Belmont                       1
Windsor Locks                 1
Northridge                    1
Lanham                        1
Sacramento                    1
Carson City                   1
West Hempstead                1
New Castle                    1
Henrico County                1
Jessup                        1
Northfield                    1
Niskayuna                     1
Raleigh-Durham                1
Denton                        1
Beloit                        1
Avon                          1
West Chester Township         1
Short Hills                   1
Aberdeen Proving Ground       1
Tarrytown                     1
Montgomery County             1
Newton                        1
Ogden                         1
Naples                        1
Novi                          1
Greenbelt                     1
Villa Park                    1
Cranbury                      1
Peterborough                  1
Chandler                      1
Cranford                      1
Roslindale                    1
Glen Allen                    1
Fort George G Meade           1
Warren                        1
ÐšÐ¸ÐµÐ²                          1
Sound Beach                   1
Muscle Shoals                 1
Redstone Arsenal              1
Oxnard                        1
Hamilton                      1
Lake Oswego                   1
Holyoke                       1
Sandy Springs                 1
Sunrise                       1
Ruskin                        1
Seal Beach                    1
KNOXVILLE                     1
Liberty Corner                1
White Plains                  1
Fallon                        1
Uniontown                     1
Fargo                         1
Collinsville                  1
Brooklawn                     1
Kenilworth                    1
Lansing                       1
Blue Bell                     1
Playa del Rey                 1
WDM                           1
Wichita                       1
Orange                        1
HOFFMAN EST                   1
Sun Prairie                   1
South Bend                    1
El Paso                       1
Bethel                        1
Appleton                      1
Grand Prairie                 1
Somerville                    1
Sandy                         1
Slater                        1
Brier                         1
Lebanon                       1
Tonawanda                     1
Malta                         1
Warrington                    1
Branchburg                    1
Sloan                         1
Upper Marlboro                1
Plainsboro Center             1

In [37]:
job_data.to_csv("output_csv/clean_job_data.csv",encoding="utf-8",index=False)